"""PR title and body generation.

See LLD #2 §2.4 for pr_generator specification.
"""

from __future__ import annotations

from docfix_bot.models import BrokenLink


def generate_pr_title(broken_links: list[BrokenLink]) -> str:
    """Generate a concise PR title.

    Args:
        broken_links: List of broken links being fixed.

    Returns:
        PR title string.
    """
    if not broken_links:
        return "fix: correct broken links"

    if len(broken_links) == 1:
        link = broken_links[0]
        return f"fix: correct broken link in {link['source_file']}"

    files = sorted({bl["source_file"] for bl in broken_links})
    if len(files) == 1:
        return f"fix: correct {len(broken_links)} broken links in {files[0]}"

    return f"fix: correct {len(broken_links)} broken links"


def generate_pr_body(broken_links: list[BrokenLink]) -> str:
    """Generate a PR description from broken link data.

    Args:
        broken_links: List of broken links being fixed.

    Returns:
        Markdown-formatted PR body.
    """
    lines = [
        "## Broken Link Fix",
        "",
        "This PR fixes broken links detected by automated scanning.",
        "",
        "### Links Fixed",
        "",
        "| File | Line | Original URL | Status | Replacement |",
        "|------|------|-------------|--------|-------------|",
    ]

    for link in broken_links:
        original = link["original_url"]
        fix = link["suggested_fix"] or "_(no fix suggested)_"
        lines.append(
            f"| `{link['source_file']}` | {link['line_number']} "
            f"| {original} | {link['status_code']} | {fix} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "This PR was generated by [Doc-Fix Bot]"
        "(https://github.com/martymcenroe/gh-link-auditor).",
        "If you'd like to opt out, add `no automated` to your CONTRIBUTING.md "
        "or contact the maintainer.",
    ])

    return "\n".join(lines)
